### ISSUE TITLE
Set mouse config to `Hovering` by default

### ISSUE THREAD

**Issue by DenisTensorWorks** [TensorWorks/TensorConfiguratorFrontend#7]
The mouse mode is currently set to `Locked` by default, change to hovering.

**Comment by mcottontensor** [comment]
Updated this to default to hovering mouse unless otherwise specified on the url.

**Comment by mcottontensor** [comment]
Turns out it resets when the stream starts. Will need to investigate further.

**Comment by DenisTensorWorks** [comment]
I found this issue in the frontend: https://github.com/EpicGames/PixelStreamingInfrastructure/issues/222

**Comment by mcottontensor** [comment]
This is now handled on the application side.
